

# Build settings
pages: ./_pages
permalink: /:categories/:title:output_ext
markdown: kramdown
include: ["_pages"]
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap


defaults:
  -
    scope:
      path:            "img/*.pdf"
    values:
      sitemap:         false
  - scope:
      path: "_pages/*"
    values:
      sitemap: false



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
